"use client";

import React, { useState, useCallback, useMemo } from "react";
import { cn } from "@/lib/utils";
import { FormStepContainer, FormSection } from "../form-step-container";
import { DocumentChecklist, DEFAULT_DOCUMENTS, DocumentItem } from "../document-checklist";
import { ReviewSummary, ReviewSection } from "../review-summary";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  SendIcon,
  FileCheckIcon,
  AlertTriangleIcon,
  CheckCircle2Icon,
  InfoIcon,
  ShieldCheckIcon,
  ClipboardListIcon,
  UserIcon,
  GraduationCapIcon,
  BriefcaseIcon,
  AwardIcon,
  FolderOpenIcon,
  BrainIcon,
  ShieldIcon,
  ChevronRightIcon,
  Loader2Icon,
} from "lucide-react";

// Types
export interface DeclarationItem {
  id: string;
  text: string;
  checked: boolean;
}

export interface StepPengajuanData {
  dokumen: DocumentItem[];
  pernyataan: DeclarationItem[];
}

export interface StepPengajuanProps {
  data: Partial<StepPengajuanData>;
  onChange: (data: StepPengajuanData) => void;
  errors?: Record<string, string>;
  onSaveDraft?: () => void;
  onSubmit?: () => void;
  // Context data for review summary
  allFormData?: Record<string, unknown>;
  jenisPengajuan?: string;
  jenisProfesi?: string;
  isSubmitting?: boolean;
}

// Declaration items (mandatory)
const DECLARATION_ITEMS: Omit<DeclarationItem, "checked">[] = [
  {
    id: "decl-1",
    text: "Saya menyatakan seluruh data yang saya berikan benar dan dapat dipertanggungjawabkan",
  },
  {
    id: "decl-2",
    text: "Saya bersedia mengikuti proses verifikasi dan asesmen kredensial",
  },
  {
    id: "decl-3",
    text: "Saya bersedia melaksanakan pelayanan sesuai kewenangan klinis yang ditetapkan",
  },
  {
    id: "decl-4",
    text: "Saya bersedia menerima hasil penilaian Tim Ad Hoc Kredensial",
  },
];

// Generate unique nomor pengajuan
const generateNomorPengajuan = (): string => {
  const year = new Date().getFullYear();
  // In real app, this would be generated by the server with sequence number
  const sequence = String(Math.floor(Math.random() * 999999) + 1).padStart(6, "0");
  return `KRD-${year}-${sequence}`;
};

export function StepPengajuan({
  data = {},
  onChange,
  errors,
  onSaveDraft,
  onSubmit,
  allFormData = {},
  jenisPengajuan,
  jenisProfesi,
  isSubmitting = false,
}: StepPengajuanProps) {
  const [showConfirmDialog, setShowConfirmDialog] = useState(false);
  const [nomorPengajuan] = useState(generateNomorPengajuan);

  // Initialize documents if not exists
  React.useEffect(() => {
    if (!data.dokumen || data.dokumen.length === 0) {
      const initialDocuments: DocumentItem[] = DEFAULT_DOCUMENTS.map((doc, index) => ({
        ...doc,
        id: `doc-${index + 1}`,
        status: "BELUM_UPLOAD" as const,
      }));
      onChange({
        ...data,
        dokumen: initialDocuments,
      } as StepPengajuanData);
    }
  }, []);

  // Initialize declarations if not exists
  React.useEffect(() => {
    if (!data.pernyataan || data.pernyataan.length === 0) {
      const initialDeclarations: DeclarationItem[] = DECLARATION_ITEMS.map((item) => ({
        ...item,
        checked: false,
      }));
      onChange({
        ...data,
        pernyataan: initialDeclarations,
      } as StepPengajuanData);
    }
  }, []);

  // Handle document changes
  const handleDocumentChange = useCallback(
    (documents: DocumentItem[]) => {
      onChange({
        ...data,
        dokumen: documents,
      } as StepPengajuanData);
    },
    [data, onChange]
  );

  // Handle declaration change
  const handleDeclarationChange = useCallback(
    (id: string, checked: boolean) => {
      const updatedDeclarations = (data.pernyataan || []).map((d) =>
        d.id === id ? { ...d, checked } : d
      );
      onChange({
        ...data,
        pernyataan: updatedDeclarations,
      } as StepPengajuanData);
    },
    [data, onChange]
  );

  // Check if all declarations are checked
  const allDeclarationsChecked = useMemo(() => {
    if (!data.pernyataan || data.pernyataan.length === 0) return false;
    return data.pernyataan.every((d) => d.checked);
  }, [data.pernyataan]);

  // Check if required documents are complete
  const isDocumentComplete = useMemo(() => {
    if (!data.dokumen || data.dokumen.length === 0) return false;
    const requiredDocs = data.dokumen.filter((d) => d.required);
    return requiredDocs.every(
      (d) => d.status === "LENGKAP" || d.status === "DIVERIFIKASI"
    );
  }, [data.dokumen]);

  // Can submit check
  const canSubmit = allDeclarationsChecked && isDocumentComplete;

  // Build review sections from form data
  const reviewSections: ReviewSection[] = useMemo(() => {
    const sections: ReviewSection[] = [];

    // Section: Data Pribadi
    sections.push({
      id: "data-pribadi",
      title: "Data Pribadi",
      icon: <UserIcon className="h-5 w-5" />,
      data: {
        Nama: (allFormData.namaLengkap as string) || "-",
        NIK: (allFormData.nik as string) || "-",
        "Tempat Lahir": (allFormData.tempatLahir as string) || "-",
        "Tanggal Lahir": (allFormData.tanggalLahir as string)
          ? new Date(allFormData.tanggalLahir as string).toLocaleDateString("id-ID", {
              day: "numeric",
              month: "long",
              year: "numeric",
            })
          : "-",
        "Jenis Kelamin": (allFormData.jenisKelamin as string) || "-",
        Alamat: (allFormData.alamat as string) || "-",
        "No. HP": (allFormData.noHp as string) || "-",
        Email: (allFormData.email as string) || "-",
      },
      isComplete: !!(allFormData.namaLengkap && allFormData.nik),
      onEdit: () => window.dispatchEvent(new CustomEvent("gotoStep", { detail: 1 })),
    });

    // Section: Pendidikan
    sections.push({
      id: "pendidikan",
      title: "Pendidikan",
      icon: <GraduationCapIcon className="h-5 w-5" />,
      data: {
        "Pendidikan Terakhir": (allFormData.pendidikanTerakhir as string) || "-",
        Institusi: (allFormData.institusiPendidikan as string) || "-",
        "Tahun Lulus": (allFormData.tahunLulus as string) || "-",
        "No. Ijazah": (allFormData.noIjazah as string) || "-",
      },
      isComplete: !!(
        allFormData.pendidikanTerakhir &&
        allFormData.institusiPendidikan
      ),
      onEdit: () => window.dispatchEvent(new CustomEvent("gotoStep", { detail: 2 })),
    });

    // Section: Data Profesi
    sections.push({
      id: "profesi",
      title: "Data Profesi",
      icon: <AwardIcon className="h-5 w-5" />,
      data: {
        "Jenis SDMK": (jenisSdmk || (allFormData.jenisSdmk as string)) || "-",
        Profesi: (jenisProfesi || (allFormData.jenisProfesi as string)) || "-",
        "No. STR": (allFormData.noStr as string) || "-",
        "Berlaku STR": (allFormData.masaBerlakuStr as string) || "-",
        "No. SIP": (allFormData.noSip as string) || "-",
        "Berlaku SIP": (allFormData.masaBerlakuSip as string) || "-",
      },
      isComplete: !!(
        allFormData.jenisProfesi &&
        allFormData.noStr
      ),
      onEdit: () => window.dispatchEvent(new CustomEvent("gotoStep", { detail: 3 })),
    });

    // Section: Pengalaman Kerja
    const riwayatKerja = allFormData.riwayatPekerjaan as Array<Record<string, unknown>> | undefined;
    sections.push({
      id: "pengalaman",
      title: "Riwayat Pengalaman",
      icon: <BriefcaseIcon className="h-5 w-5" />,
      data: {
        "Jumlah Riwayat Pekerjaan": riwayatKerja?.length
          ? `${riwayatKerja.length} entri`
          : "Tidak ada data",
        "Jumlah Pelatihan": (
          allFormData.pelatihan as Array<Record<string, unknown>> | undefined
        )?.length
          ? `${(allFormData.pelatihan as Array<Record<string, unknown>>).length} entri`
          : "Tidak ada data",
      },
      isComplete: !!(riwayatKerja && riwayatKerja.length > 0),
      onEdit: () => window.dispatchEvent(new CustomEvent("gotoStep", { detail: 5 })),
    });

    // Section: Portofolio
    const portofolioList = allFormData.portofolio as Array<Record<string, unknown>> | undefined;
    sections.push({
      id: "portofolio",
      title: "Portofolio",
      icon: <FolderOpenIcon className="h-5 w-5" />,
      data: {
        "Total Portofolio": portofolioList?.length
          ? `${portofolioList.length} item`
          : "Tidak ada data",
      },
      isComplete: true, // Optional section
      onEdit: () => window.dispatchEvent(new CustomEvent("gotoStep", { detail: 6 })),
    });

    // Section: Kompetensi
    const kompetensiList = allFormData.kompetensi as Array<Record<string, unknown>> | undefined;
    const mandiriCount = kompetensiList?.filter(
      (k) => k.level === "KOMPETEN_MANDIRI"
    ).length || 0;
    const supervisiCount = kompetensiList?.filter(
      (k) => k.level === "KOMPETEN_SUPERVISI"
    ).length || 0;
    sections.push({
      id: "kompetensi",
      title: "Self Assessment Kompetensi",
      icon: <BrainIcon className="h-5 w-5" />,
      data: {
        "Total Kompetensi Dinilai": kompetensiList?.length
          ? `${kompetensiList.length} kompetensi`
          : "Tidak ada data",
        "Kompeten Mandiri": `${mandiriCount} kompetensi`,
        "Kompeten Supervisi": `${supervisiCount} kompetensi`,
      },
      isComplete: !!(kompetensiList && kompetensiList.length > 0),
      onEdit: () => window.dispatchEvent(new CustomEvent("gotoStep", { detail: 6 })),
    });

    // Section: Kewenangan Klinis
    const kewenanganList = allFormData.kewenanganKlinis as Array<Record<string, unknown>> | undefined;
    const kewenanganMandiri = kewenanganList?.filter(
      (k) => k.level === "MANDIRI"
    ).length || 0;
    const kewenanganSupervisi = kewenanganList?.filter(
      (k) => k.level === "DENGAN_SUPERVISI"
    ).length || 0;
    sections.push({
      id: "kewenangan",
      title: "Usulan Kewenangan Klinis",
      icon: <ShieldIcon className="h-5 w-5" />,
      data: {
        "Diajukan Mandiri": `${kewenanganMandiri} kewenangan`,
        "Diajukan Supervisi": `${kewenanganSupervisi} kewenangan`,
        "Total Diajukan": `${kewenanganMandiri + kewenanganSupervisi} kewenangan`,
      },
      isComplete: kewenanganMandiri + kewenanganSupervisi > 0,
      onEdit: () => window.dispatchEvent(new CustomEvent("gotoStep", { detail: 7 })),
    });

    return sections;
  }, [allFormData, jenisSdmk, jenisProfesi]);

  // Handle final submission
  const handleSubmit = useCallback(() => {
    setShowConfirmDialog(true);
  }, []);

  // Confirm submission
  const handleConfirmSubmit = useCallback(() => {
    setShowConfirmDialog(false);
    onSubmit?.();
  }, [onSubmit]);

  // Cancel submission
  const handleCancelSubmit = useCallback(() => {
    setShowConfirmDialog(false);
  }, []);

  return (
    <FormStepContainer
      stepNumber={8}
      totalSteps={8}
      title="Pengajuan Kredensial"
      description="Periksa kelengkapan dokumen, berikan pernyataan, dan ajukan kredensial Anda"
      onSaveDraft={onSaveDraft}
      showSubmit={true}
      canProceed={canSubmit}
      isSubmitting={isSubmitting}
      onNext={handleSubmit}
      icon={<SendIcon className="h-5 w-5" />}
    >
      {/* Nomor Pengajuan Display */}
      <div className="p-4 rounded-xl bg-gradient-to-r from-[#1e3a5f] to-[#2d4a6f] dark:from-[#0f2744] dark:to-[#1e3a5f] flex items-center justify-between">
        <div>
          <p className="text-white/70 text-xs uppercase tracking-wider font-medium">
            Nomor Pengajuan
          </p>
          <p className="text-white font-mono font-bold text-lg mt-1">{nomorPengajuan}</p>
        </div>
        <Badge variant="outline" className="border-white/30 text-white bg-white/10">
          Draft
        </Badge>
      </div>

      {/* Section 1: Dokumen Checklist */}
      <FormSection
        title="Dokumen Checklist"
        description="Pastikan semua dokumen wajib telah diunggah dengan lengkap"
      >
        <DocumentChecklist
          documents={data.dokumen || []}
          onChange={handleDocumentChange}
          showDetails={true}
        />

        {/* Error message */}
        {errors?.dokumen && (
          <div className="mt-3 flex items-center gap-2 text-sm text-red-600 bg-red-50 dark:bg-red-900/20 p-3 rounded-lg">
            <AlertTriangleIcon className="h-4 w-4 shrink-0" />
            {errors.dokumen}
          </div>
        )}
      </FormSection>

      {/* Section 2: Pernyataan (Declarations) */}
      <FormSection
        title="Pernyataan dan Kesepakatan"
        description="Baca dan setujui seluruh pernyataan di bawah ini untuk dapat mengajukan kredensial"
      >
        <Card className={cn(
          "overflow-hidden transition-all duration-200",
          allDeclarationsChecked
            ? "border-emerald-200 bg-emerald-50/30 dark:bg-emerald-900/10"
            : "border-amber-200 bg-amber-50/30 dark:bg-amber-900/10"
        )}>
          <CardContent className="p-4 md:p-6">
            {/* Header */}
            <div className="flex items-start gap-3 mb-4 pb-4 border-b border-slate-200 dark:border-slate-700">
              <div className={cn(
                "w-10 h-10 rounded-full flex items-center justify-center shrink-0",
                allDeclarationsChecked
                  ? "bg-emerald-100 dark:bg-emerald-900/30 text-emerald-600"
                  : "bg-amber-100 dark:bg-amber-900/30 text-amber-600"
              )}>
                <ShieldCheckIcon className="h-5 w-5" />
              </div>
              <div>
                <h4 className="font-semibold text-slate-800 dark:text-slate-200">
                  Pernyataan Wajib
                </h4>
                <p className="text-sm text-slate-500 mt-0.5">
                  Semua pernyataan harus dicentang untuk melanjutkan pengajuan
                </p>
              </div>
              <Badge
                variant="outline"
                className={cn(
                  "shrink-0 ml-auto",
                  allDeclarationsChecked
                    ? "border-emerald-300 text-emerald-600 bg-emerald-50"
                    : "border-amber-300 text-amber-600 bg-amber-50"
                )}
              >
                {data.pernyataan?.filter((d) => d.checked).length || 0}/{DECLARATION_ITEMS.length}
              </Badge>
            </div>

            {/* Declarations List */}
            <div className="space-y-3">
              {(data.pernyataan || []).map((declaration, index) => (
                <label
                  key={declaration.id}
                  htmlFor={declaration.id}
                  className={cn(
                    "flex items-start gap-3 p-3 rounded-lg cursor-pointer transition-all border",
                    declaration.checked
                      ? "bg-emerald-50/50 dark:bg-emerald-900/20 border-emerald-200 dark:border-emerald-800 hover:bg-emerald-50 dark:hover:bg-emerald-900/30"
                      : "bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-800/50"
                  )}
                >
                  <Checkbox
                    id={declaration.id}
                    checked={declaration.checked}
                    onCheckedChange={(checked) =>
                      handleDeclarationChange(declaration.id, checked as boolean)
                    }
                    className="mt-0.5 data-[state=checked]:bg-emerald-500 data-[state=checked]:border-emerald-500"
                  />
                  <span className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
                    <span className="font-medium text-slate-500 mr-2">{index + 1}.</span>
                    {declaration.text}
                  </span>
                </label>
              ))}
            </div>

            {/* Warning if not all checked */}
            {!allDeclarationsChecked && (
              <div className="mt-4 flex items-center gap-2 text-sm text-amber-600 bg-amber-50 dark:bg-amber-900/20 p-3 rounded-lg">
                <AlertTriangleIcon className="h-4 w-4 shrink-0" />
                <span>
                  Centang semua pernyataan untuk mengaktifkan tombol{" "}
                  <strong>AJUKAN KREDENSIAL</strong>
                </span>
              </div>
            )}

            {/* Success state */}
            {allDeclarationsChecked && (
              <div className="mt-4 flex items-center gap-2 text-sm text-emerald-600 bg-emerald-50 dark:bg-emerald-900/20 p-3 rounded-lg">
                <CheckCircle2Icon className="h-4 w-4 shrink-0" />
                <span>Semua pernyataan telah disetujui</span>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Error message */}
        {errors?.pernyataan && (
          <div className="mt-3 flex items-center gap-2 text-sm text-red-600 bg-red-50 dark:bg-red-900/20 p-3 rounded-lg">
            <AlertTriangleIcon className="h-4 w-4 shrink-0" />
            {errors.pernyataan}
          </div>
        )}
      </FormSection>

      {/* Section 3: Review Summary */}
      <FormSection
        title="Ringkasan Pengajuan"
        description="Periksa kembali semua data sebelum mengajukan kredensial"
      >
        <ReviewSummary
          sections={reviewSections}
          onSubmit={handleSubmit}
          isSubmitting={isSubmitting}
          showConfirmation={false} // We have our own confirmation dialog
          confirmTitle="Konfirmasi Pengajuan Kredensial"
          confirmMessage={`Anda akan mengajukan kredensial dengan nomor ${nomorPengajuan}. Pastikan semua data yang Anda masukkan sudah benar dan lengkap.`}
        />

        {/* Error message */}
        {errors?.review && (
          <div className="mt-3 flex items-center gap-2 text-sm text-red-600 bg-red-50 dark:bg-red-900/20 p-3 rounded-lg">
            <AlertTriangleIcon className="h-4 w-4 shrink-0" />
            {errors.review}
          </div>
        )}
      </FormSection>

      {/* Important Information */}
      <div className="p-4 rounded-xl bg-blue-50 dark:bg-blue-900/20 border border-blue-200 dark:border-blue-800 flex items-start gap-3">
        <InfoIcon className="h-5 w-5 text-blue-500 shrink-0 mt-0.5" />
        <div className="text-sm text-blue-800 dark:text-blue-300 space-y-2">
          <p className="font-medium">Informasi Penting Sebelum Mengajukan</p>
          <ul className="list-disc list-inside space-y-1 ml-2">
            <li>Pastikan semua data yang dimasukkan adalah akurat dan dapat dibuktikan</li>
            <li>Dokumen yang diunggah harus jelas terbaca dan masih berlaku</li>
            <li>Pengajuan yang telah dikirim tidak dapat dibatalkan secara otomatis</li>
            <li>Anda dapat memantau status pengajuan melalui halaman tracking</li>
            <li>Hubungi admin jika ada kesalahan data setelah pengajuan</li>
          </ul>
        </div>
      </div>

      {/* Custom Confirmation Dialog */}
      <Dialog open={showConfirmDialog} onOpenChange={setShowConfirmDialog}>
        <DialogContent className="sm:max-w-lg">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-3">
              <div className="w-12 h-12 rounded-full bg-gradient-to-br from-[#059669] to-[#0d9488] flex items-center justify-center">
                <SendIcon className="h-6 w-6 text-white" />
              </div>
              Konfirmasi Pengajuan Kredensial
            </DialogTitle>
            <DialogDescription className="text-base pt-2">
              Apakah Anda yakin ingin mengajukan kredensial ini?
            </DialogDescription>
          </DialogHeader>

          {/* Nomor Pengajuan Info */}
          <div className="py-4 space-y-4">
            <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700">
              <p className="text-sm text-slate-500">Nomor Pengajuan</p>
              <p className="text-xl font-bold font-mono text-[#1e3a5f] dark:text-teal-400">
                {nomorPengajuan}
              </p>
            </div>

            <div className="p-4 rounded-xl bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-200 dark:border-emerald-800">
              <p className="text-sm text-emerald-800 dark:text-emerald-300 font-medium mb-2">
                Dengan menekan tombol &quot;AJUKAN KREDENSIAL&quot;, Anda menyatakan bahwa:
              </p>
              <ul className="text-sm text-emerald-700 dark:text-emerald-400 space-y-1.5 list-disc list-inside">
                <li>Semua data yang dimasukkan adalah benar dan akurat</li>
                <li>Dokumen yang diunggah adalah dokumen asli yang sah</li>
                <li>Bersedia menerima konsekuensi jika terbukti data palsu</li>
                <li>Menyetujui syarat dan ketentuan yang berlaku</li>
              </ul>
            </div>

            <div className="p-4 rounded-xl bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800">
              <p className="text-sm text-amber-800 dark:text-amber-300 font-medium flex items-start gap-2">
                <AlertTriangleIcon className="h-4 w-4 shrink-0 mt-0.5" />
                Proses pengajuan tidak dapat dibatalkan setelah dikirim.
              </p>
            </div>
          </div>

          <DialogFooter className="gap-2 sm:gap-0 sm:flex-col-reverse">
            <Button
              variant="outline"
              onClick={handleCancelSubmit}
              disabled={isSubmitting}
              className="w-full sm:w-auto gap-2"
            >
              Batalkan
            </Button>
            <Button
              onClick={handleConfirmSubmit}
              disabled={isSubmitting}
              className="w-full sm:w-auto gap-2 bg-gradient-to-r from-[#059669] to-[#0d9488] hover:from-emerald-600 hover:to-teal-600 text-white shadow-lg shadow-emerald-200 dark:shadow-emerald-900/30 px-6"
            >
              {isSubmitting ? (
                <>
                  <Loader2Icon className="h-4 w-4 animate-spin" />
                  Memproses Pengajuan...
                </>
              ) : (
                <>
                  AJUKAN KREDENSIAL
                  <ChevronRightIcon className="h-4 w-4" />
                </>
              )}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </FormStepContainer>
  );
}

export default StepPengajuan;
